version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAKSTS28OctProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: siqagituser
  gitUrl: https://github.com/prabhakarsag
  gitUsername: siqagituser
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: siqagituser
  gitUrl: https://github.com/prabhakarsag
  gitUsername: siqagituser
  gitBranch: main
services:
- serviceName: project.siqaksts28oct.integrations:JMS_SSL
  packages:
  - name: SIQAKSTS28OctProject
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: softwareag
- serviceName: publisher:publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2015
